# Generated by Django 6.0.4 on 2026-04-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('DESCARTABLE', 'Descartable'), ('INSTRUMENTAL', 'Instrumental')], max_length=50)),
                ('zona_medica', models.CharField(max_length=100)),
                ('codigo_ocasa', models.CharField(max_length=50, unique=True)),
                ('procedencia', models.CharField(max_length=100)),
                ('lugar_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_lote', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('vencimiento', models.DateField()),
                ('nro_deposito', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('drogueria', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('acotaciones', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.producto')),
            ],
        ),
    ]
