# Generated by Django 6.0.4 on 2026-04-14 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Ingreso de stock)'), ('SALIDA', 'Salida (Consumo/Uso)'), ('TRANSFERENCIA', 'Transferencia (Hacia otro sector)'), ('DEVOLUCION', 'Devolución'), ('BAJA', 'Baja (Vencimiento/Deterioro)')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.TextField(blank=True, help_text='Ej: Exportación rural a Farmacia X', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
