# Generated by Django 6.0.4 on 2026-04-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cod_barra', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lote',
            name='acotaciones',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='drogueria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='lugar_origen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='zona_medica',
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='qr_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nivel_riesgo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='refrigeracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('BAJA', 'Baja/Vencimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='procedencia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('MED', 'Medicamento'), ('DES', 'Descartable')], max_length=50),
        ),
        migrations.AddField(
            model_name='lote',
            name='laboratorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.laboratorio'),
        ),
    ]
