# Generated by Django 6.0.5 on 2026-05-16 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_laboratorio_remove_lote_acotaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hueco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nro_deposito', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado')], default='LIBRE', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='hueco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.hueco'),
        ),
    ]
