# Generated by Django 6.0.5 on 2026-06-10 23:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_hueco_lote_hueco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Departamento')),
                ('piso_ubicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación/Piso')),
            ],
        ),
        migrations.RemoveField(
            model_name='hueco',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='hueco',
            name='nro_deposito',
        ),
        migrations.RemoveField(
            model_name='hueco',
            name='sector',
        ),
        migrations.AddField(
            model_name='hueco',
            name='cantidad_actual',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AddField(
            model_name='hueco',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(default=100, verbose_name='Capacidad Máxima de Almacenaje'),
        ),
        migrations.AddField(
            model_name='hueco',
            name='codigo_identificador',
            field=models.CharField(default='PROV-000', max_length=50, unique=True, verbose_name='Código de Hueco/Botiquín'),
        ),
        migrations.AddField(
            model_name='hueco',
            name='insumo_nombre',
            field=models.CharField(default='Insumo Genérico', max_length=100, verbose_name='Medicamento / Insumo'),
        ),
        migrations.AlterField(
            model_name='hueco',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Con Stock'), ('CRITICO', 'Stock Crítico'), ('VACIO', 'Sin Stock')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='hueco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inventario.hueco', verbose_name='Hueco Asignado'),
        ),
        migrations.AddField(
            model_name='hueco',
            name='departamento_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huecos', to='inventario.departamento', verbose_name='Departamento Destino'),
        ),
        migrations.CreateModel(
            name='HistorialRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo_retirado', models.CharField(max_length=100, verbose_name='Insumo Extraído')),
                ('ubicacion_en_retiro', models.CharField(max_length=150, verbose_name='Ubicación exacta al momento del retiro')),
                ('cantidad_retirada', models.PositiveIntegerField(verbose_name='Cantidad Retirada')),
                ('fecha_retiro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Retiro')),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento', verbose_name='Departamento/Uso Destinado')),
                ('hueco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiros', to='inventario.hueco', verbose_name='Hueco de Origen')),
                ('usuario_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Responsable')),
            ],
        ),
    ]
