# Generated by Django 6.0.5 on 2026-06-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_departamento_remove_hueco_codigo_and_more'),
        ('inventario', '0006_auto_20260625_2324'),
    ]

    operations = [
    ]
